// Created and modifed by Nathan Loveless 12/20/19
//*** NOTE:  THIS IS A TEST DATA FILE ONLY ***/
export const userData = {
    id: '10',
    first_name: 'Nathan',
    last_name: 'Loveless',
    location: 'Northfield, VT',
    contact: 'https://www.linkedin.com/in/nathanloveless/',
    username: 'nathansl2003',
    password: 'password',
    email_address: 'nathansl2003@yahoo.com',
    avatar_url: ''
}

export const recipes = [{ 
    id: '0',
    chefId: '10',
    title: 'Egg-in-a-Hole with Spinach & Bacon',
    image: '/images/egginhole.JPG',
    mealType: 'Breakfast',
    description: 'When you make this cute breakfast-for-dinner recipe, also known as toad-in-a-hole or a one-eyed jack, you can vary it by using kale or even Swiss chard in place of the spinach.',
    instructions: 'Preheat oven to 425°F. Coat a large baking sheet with cooking spray. Cook bacon in a large cast-iron skillet over medium heat until crisp, 7 to 9 minutes. Drain on paper towels. Pour the bacon fat into a small heatproof bowl. If necessary, add oil to make 2 tablespoons. Meanwhile, heat 1 tablespoon oil in a large saucepan over medium heat. Add garlic and cook, stirring, about 30 seconds. Add spinach by the handful and cook, stirring, until wilted, about 5 minutes. Transfer to a colander; press out excess liquid. Return the spinach to the pan and season with vinegar, ¼ teaspoon pepper and salt. Cut a 3½-inch hole in the middle of each slice of bread. (Save the rounds for another use, if desired.) Heat 1 tablespoon of the reserved bacon fat in the skillet over medium-high heat. Cook 2 slices of bread, pressing with a spatula, until lightly browned, 1 to 3 minutes per side. Transfer to the prepared baking sheet. Repeat with the remaining fat and bread. Fill each hole with spinach. Make a deep well in the spinach and break an egg into each well. Bake, rotating the baking sheet 180 degrees about halfway through, 10 to 14 minutes for soft-set yolks. Serve sprinkled with crumbled bacon and the remaining ¼ teaspoon pepper.',
    isFetching: false,
    error: '' 
},
{ 
    id: '1',
    chefId: '10',
    title: 'Quick Pastrami Hash & Eggs',
    image: './images/quickpastramihasheggs.JPG',
    mealType: 'Breakfast',
    description: 'When we\'re in a hurry, we love to have breakfast for dinner. Precooked diced potatoes--available in the refrigerated section of most supermarkets--help make this pastrami hash ultra-fast. (If you have leftover cooked potatoes, use about 3 cups diced cooked potatoes instead.) Serve with rye toast and sautéed spinach.',
    instructions: 'Heat oil in a large skillet over medium-high heat. Reduce heat to medium and add potatoes, onion, bell pepper, paprika and ¼ teaspoon each salt and pepper. Stir to combine, then spread in an even layer in the pan and cook, undisturbed, for 3 minutes. Stir in pastrami, spread back into an even layer and cook undisturbed again until a crust starts to form on the bottom, about 5 minutes more. Remove from the heat and cover to keep warm. Just after you add the pastrami to the hash, coat a large nonstick skillet with cooking spray and place over medium heat. Crack each egg into a small bowl and slip them, one at a time, into the skillet, taking care not to break the yolks. Season with the remaining pinch of salt and pepper. Reduce heat to medium-low, cover and cook undisturbed for about 2 minutes for soft-set yolks. Divide the hash among 4 plates and top each serving with an egg.',
    isFetching: false,
    error: '' 
},
{ 
    id: '2',
    chefId: '10',
    title: 'Broccoli, Beef & Potato Hotdish',
    image: './images/brocbeefpothotdish.JPG',
    mealType: 'Lunch',
    description: 'This easy casserole, full of ground beef, roasted broccoli and topped with hash browns, was inspired by the classic Minnesota Tater Tot hotdish. Roasting the broccoli before adding it to the casserole gives the whole dish a much more complex and exciting flavor, but it&apos;   1`s by no means necessary. If you want to keep it simple, skip roasting the broccoli (Step 2) and use 6 cups frozen broccoli, thawed, in its place (omit 1 tablespoon oil, as well). ',
    instructions: 'Toss broccoli with 1 tablespoon oil in a large bowl. Spread out on a baking sheet and roast, stirring once halfway though, until just soft and browned in spots, about 15 minutes. Meanwhile, heat the remaining 1 tablespoon oil in a large skillet over medium heat. Add beef and onion and cook, breaking up the beef with a wooden spoon, until the beef is browned and the onion is softened, 10 to 12 minutes. Stir in Worcestershire, garlic powder and ¼ teaspoon salt. Set aside. Whisk milk and cornstarch in a large saucepan. Bring to a boil over medium-high heat, whisking often, until bubbling and thickened enough to coat the back of a spoon, 6 to 8 minutes total. Remove from the heat and stir in Cheddar, ¾ teaspoon salt and turmeric until the cheese is melted. Spread the beef mixture in a 9-by-13-inch (or similar 3-quart) baking dish. Top with the broccoli and pour the cheese sauce evenly over the top. Combine potatoes, egg, pepper and the remaining ¼ teaspoon salt in a medium bowl. Sprinkle evenly over the casserole. Coat the top with cooking spray. Bake the casserole until it is bubbling and the potatoes are beginning to brown, about 40 minutes. Sprinkle with paprika. Let stand for 10 minutes before serving.',
    isFetching: false,
    error: '' 
},
{ 
    id: '3',
    chefId: '10',
    title: 'Healthy Green Bean Casserole',
    image: './images/healthygreenbeencasserole.JPG',
    mealType: 'Lunch',
    description: 'Typical green bean casseroles bathe ingredients in a heavy cream sauce and top them with buttered breadcrumbs or cheese. Our healthier version saves about 160 calories and 12 grams of saturated fat compared to a traditional recipe.',
    instructions: 'Position racks in upper and lower third of oven; preheat to 425°F. Toss green beans in a large bowl with 1 tablespoon oil until well coated. Divide between 2 baking sheets and spread in an even layer. Roast, stirring once and rotating the pans top to bottom about halfway through, until tender and beginning to brown, 20 to 25 minutes. Meanwhile, heat 1 tablespoon oil in a large saucepan over medium heat. Add onion and cook, stirring frequently, until very soft and golden brown, 5 to 8 minutes. Add flour, salt and pepper; cook, stirring, for 1 minute more. Add milk and continue to stir, scraping up any browned bits. Cook, stirring, until the sauce bubbles and thickens enough to coat the back of a spoon, about 4 minutes. Remove from the heat. (See Tips) When the green beans are done, remove from the oven. Preheat the broiler. Transfer half the green beans to a 2-quart, broiler-safe baking dish. Spread half the sauce over the green beans. Add the remaining green beans and top with the remaining sauce. Combine breadcrumbs and the remaining 1 tablespoon oil in a small bowl (skip this step if you are topping with cheese). Sprinkle the breadcrumb mixture (or cheese) over the gratin. Place under the broiler and broil, watching closely, until the gratin is bubbling and beginning to brown on top, 1 to 5 minutes, depending on your broiler. Let stand for 10 minutes before serving.',
    isFetching: false,
    error: '' 
},
{ 
    id: '4',
    chefId: '10',
    title: 'Parmesan-Crusted Chicken Tenders',
    image: './images/parmesancrustedchickentenders.JPG',
    mealType: 'Dinner',
    description: 'Crispy, Parmesan-flecked chicken tenders dipped in marinara sauce is an easy dinner the whole family will love. Dipping them in a mixture of plain yogurt with chopped fresh basil would be tasty too. Serve with sautéed green beans and roasted sweet potato wedges.',
    instructions: 'Preheat oven to 450°F. Place a large wire rack on a baking sheet and coat with cooking spray. Place flour in a shallow dish. Lightly beat eggs in another shallow dish. Combine Parmesan and breadcrumbs in a third shallow dish. Toss tenders with Italian seasoning, garlic powder and salt in a medium bowl. Coat each tender in flour, shaking off any excess. Dip in egg and let any excess drip off. Then roll in the breadcrumb mixture. Place the tenders on the prepared rack. Generously coat the top of each tender with cooking spray. Bake for 10 minutes. Turn each tender over and coat with cooking spray. Continue baking until the outside is crisp and the tenders are cooked through, about 10 minutes more. Serve the tenders with marinara sauce for dipping.',
    isFetching: false,
    error: '' 
},
{ 
    id: '5',
    chefId: '10',
    title: 'Roasted Chickens',
    image: './images/roastedchickens.JPG',
    mealType: 'Dinner',
    description: 'In this easy roast chicken recipe, two whole birds cook side-by-side on one pan, which means you only have to heat the oven once but you&apos;ll have enough leftover chicken for days. Rotating the chickens on the pan during roasting ensures all sides are evenly cooked and golden brown.',
    instructions: 'Preheat oven to 450°F. Coat a large rimmed baking sheet with cooking spray. Let chickens stand at room temperature for 30 minutes. Thoroughly pat dry with paper towels, inside and out. Gently separate the skin from the meat and season under the skin and inside the cavity with salt and pepper. Tie the legs together with kitchen string, mostly closing the cavity opening. Tuck the wing tips under the chickens. Place onion, celery and carrot on the prepared baking sheet. Brush the chickens with oil and set on top of the vegetables, about 2 inches apart. Roast in the center of the oven for 40 minutes. Using tongs and a spatula to help you, rotate each chicken 180 degrees (so the side facing in is now facing out). Continue roasting until an instant-read thermometer inserted into the thickest part of the thigh, without touching bone, registers at least 165°F, 20 to 30 minutes more. Tilt each chicken so the juice from the cavity runs onto the pan. Transfer the chickens to a clean cutting board. Let rest 15 minutes. Remove the string before carving.',
    isFetching: false,
    error: '' 
},
{ 
    id: '6',
    chefId: '10',
    title: 'Pork Chops au Poivre',
    image: './images/porkchopsaupoivre.JPG',
    mealType: 'Dinner',
    description: 'Turn your dining room into a French bistro when you dress up pepper-crusted pork chops with a rich, creamy brandy sauce. Serve with roasted sweet potato slices and green beans.',
    instructions: 'Combine pepper and ¼ teaspoon salt in a small bowl. Pat the mixture onto both sides of each pork chop. Place flour in a shallow dish; dredge each chop in the flour, shaking off any excess. Heat oil in a large skillet over medium-high heat. Add the chops, reduce heat to medium and cook until browned and just cooked through, 2 to 3 minutes per side. Transfer to a plate and tent with foil to keep warm. Reduce heat to medium-low. Add shallot to the pan and cook, stirring, until softened, about 1 minute. Add brandy and cook, stirring and scraping up any browned bits, until most of the liquid has evaporated, 1 to 2 minutes. Remove from the heat; stir in sour cream and the remaining ¼ teaspoon salt. Serve the pork chops with the sauce.',
    isFetching: false,
    error: '' 
},
{ 
    id: '7',
    chefId: '10',
    title: 'Oven-Barbecued Pork Chops',
    image: './images/ovenbarbecuedporkchops.JPG',
    mealType: 'Dinner',
    description: 'Need a little summertime flavor? Try this swift recipe and enjoy a “barbecue” indoors. Make it a meal: Serve with coleslaw and cornbread.',
    instructions: 'Preheat oven to 400°F. Sprinkle pork chops with salt and pepper. Heat 2 teaspoons oil in a large ovenproof skillet over high heat. Add the pork chops and cook until beginning to brown, 1 to 2 minutes per side. Transfer to a plate. Add the remaining 1 teaspoon oil to the pan. Add onion and cook, stirring, until softened, 3 to 4 minutes. Stir in garlic and cook, stirring, until fragrant, 30 seconds. Add orange juice and cook until most of the liquid has evaporated, 30 seconds to 1 minute. Stir in barbecue sauce. Return the pork chops to the pan, turning several times to coat with the sauce. Transfer the pan to the oven and bake until the pork chops are barely pink in the middle and an instant-read thermometer registers 145°F, 6 to 10 minutes. Serve the sauce over the pork chops.',
    isFetching: false,
    error: '' 
},
{ 
    id: '8',
    chefId: '10',
    title: 'Apricot-Bulgur Pudding Cake with Custard Sauce',
    image: './images/apricotbulgurpuddingcake.JPG',
    mealType: 'Dessert',
    description: 'Don&apos;t be put off by “bulgur” and “cake” in the same title. (Think rice pudding but with bulgur.) Whether you use coarser-textured bulgur (our preference) or fine, the cooked bulgur (Step 1) should resemble cooked oatmeal.',
    instructions: 'Combine apricots, sugar, orange zest, orange juice and water in a medium saucepan. Bring to a boil; reduce heat to a simmer and cook, stirring occasionally, until the apricots are very tender, about 10 minutes. Stir in bulgur and increase heat to high. Return to a boil; reduce heat to a low simmer and cook, stirring occasionally, until the bulgur is tender, about 20 minutes. (The mixture will be the consistency of cooked oatmeal.) Remove from the heat and let cool, uncovered, for 10 minutes. Position a rack in the center of the oven; preheat to 350F. Whisk egg yolks and milk in a large bowl until well combined. Slowly whisk in the bulgur mixture. Beat egg whites in a medium bowl with a mixer on medium-high speed until stiff peaks form. Fold into the bulgur mixture using a rubber spatula. Transfer the batter to an 8-inch-square baking dish. Push brown sugar through a sieve evenly over the batter. Place the baking dish in a roasting pan and transfer to the oven. Pour very hot tap water into the roasting pan until it comes about halfway up the sides of the baking dish. Bake until the cake is puffed and golden, 30 to 40 minutes. Carefully remove the baking dish from the hot water, transfer to a wire rack and let cool to room temperature before serving. Top each serving with some Custard Sauce and a sprinkling of pistachios.',
    isFetching: false,
    error: '' 
},
{ 
    id: '9',
    chefId: '10',
    title: 'Greek Yogurt Cheesecake with Ouzo-Poached Figs',
    image: './images/greekyogurtcheesecake.JPG',
    mealType: 'Dessert',
    description: 'This tangy yogurt cheesecake is topped with ouzo-poached figs inspired by sikomaida, a traditional delicacy from Corfu made with dried figs macerated and kneaded with ouzo and pepper, which are formed into disks and dried in chestnut leaves. It&apos;s also delicious with seasonal fruits, fresh or dried and poached, or with whole preserves.',
    instructions: 'To prepare crust: Preheat oven to 325°F. Put a kettle of water on to heat for the water bath. Coat a 10-inch springform pan with cooking spray; tightly wrap the bottom and outside with a double layer of foil. Process Melba toasts and walnuts in a food processor until fine crumbs form. Transfer to a medium bowl. Add oil and 2 tablespoons sugar and toss until evenly moist. Press the crumb mixture into the bottom of the pan. Bake until lightly browned, about 10 minutes. Transfer to a wire rack and let cool to room temperature, about 30 minutes. To prepare cheesecake: When the crust is almost cool, beat cream cheese and 1 cup sugar in a large mixing bowl with an electric mixer until smooth. Add yogurt, egg whites and cinnamon; beat until well blended. Pour the batter over the cooled crust. Place the cheesecake in a roasting pan and pour in enough boiling water to come 1 inch up the outside of the springform pan. Bake the cheesecake in the center of the oven until set around the edges but the center still jiggles, about 45 minutes. Turn off the oven and let the cheesecake sit in the oven with the door ajar for 1 hour. Let cool on a wire rack for 1 hour more. To prepare topping: Meanwhile, place figs in a small bowl, cover with warm water and let soak for 1 hour. Strain the figs, reserving the soaking water. Strain the soaking water into a medium saucepan. Add ouzo (or wine); bring to a boil over high heat. Add geranium leaves (if using), cinnamon stick, orange zest and the figs. Reduce the heat to medium and cook until the figs are plump and the liquid is the consistency of a thin syrup, 10 to 15 minutes. Remove the figs with a slotted spoon and set aside to cool. Stir ½ cup sugar into the liquid, adjust the heat to maintain a gentle simmer, and cook until the liquid is reduced by half, 15 to 25 minutes. Discard the geranium leaves, cinnamon stick and orange zest. Chop the figs and return them to the syrup. Remove the pan sides from the cheesecake. Serve each slice topped with some of the fig sauce and a rose geranium leaf, if desired.',
    isFetching: false,
    error: ''
}
]

export const ingredients = [{
        id: '0',
        recipe_id: '0', 
        ingredient: 'Bacon',
        quantity: '3',
        measurement: 'slice',
        notes: '',
    },
    {
        id: '1',
        recipe_id: '0', 
        ingredient: 'Extra-Virgin Olive Oil',
        quantity: '1',
        measurement: 'Tbsp',
        notes: 'Plus more if needed',
    },
    {
        id: '2',
        recipe_id: '0', 
        ingredient: 'Garlic Clove',
        quantity: '3',
        measurement: 'each',
        notes: '',
    },
    {
        id: '3',
        recipe_id: '0', 
        ingredient: 'Spinach',
        quantity: '1',
        measurement: 'lb',
        notes: '(about 16 cups) tough stems removed)',
    },
    {
        id: '4',
        recipe_id: '0', 
        ingredient: 'Red Wine Vinegar',
        quantity: '1',
        measurement: 'tsp',
        notes: '',
    },
    {
        id: '5',
        recipe_id: '0', 
        ingredient: 'Black Pepper, Ground',
        quantity: '1/2',
        measurement: 'tsp',
        notes: 'divided to 1/4 tsp',
    },
    {
        id: '6',
        recipe_id: '0', 
        ingredient: 'Salt',
        quantity: '1/4',
        measurement: 'tsp',
        notes: '',
    },
    {
        id: '7',
        recipe_id: '0', 
        ingredient: 'Country-Style Whole Wheat Bread',
        quantity: '4',
        measurement: 'slice',
        notes: '3/4 - 1 inch thick',
    },
    {
        id: '8',
        recipe_id: '1',
        ingredient: 'Extra-Virgin Olive Oil',
        quantity: '2',
        measurement: 'Tbsp',
        notes: '',
    },
    {
        id: '9',
        recipe_id: '1',
        ingredient: 'Potato',
        quantity: '18',
        measurement: 'oz',
        notes: 'Peeled or unpeeled, diced, cooked',
    },
    {
        id: '10',
        recipe_id: '1',
        ingredient: 'Onion',
        quantity: '1',
        measurement: 'each',
        notes: 'quartered, thinly sliced',
    },
    {
        id: '11',
        recipe_id: '1',
        ingredient: 'Bell Pepper, Green',
        quantity: '1',
        measurement: 'each',
        notes: 'diced',
    },
    {
        id: '12',
        recipe_id: '1',
        ingredient: 'Paprika',
        quantity: '1',
        measurement: 'tsp',
        notes: '',
    },
    {
        id: '13',
        recipe_id: '1',
        ingredient: 'Salt',
        quantity: '1/4',
        measurement: 'tsp',
        notes: 'divided 1/8 tsp',
    },
    {
        id: '14',
        recipe_id: '1',
        ingredient: 'Black Pepper, Ground',
        quantity: '1/4',
        measurement: 'tsp',
        notes: 'divided 1/8 tsp',
    },
    {
        id: '15',
        recipe_id: '1',
        ingredient: 'Pastrami',
        quantity: '5',
        measurement: 'oz',
        notes: 'Sliced, diced (about 1 generous cup)',
    },
    {
        id: '16',
        recipe_id: '1',
        ingredient: 'Egg',
        quantity: '4',
        measurement: 'each',
        notes: '',
    },
    {
        id: '17',
        recipe_id: '2',
        ingredient: 'Broccoli',
        quantity: '1 1/2',
        measurement: 'lb',
        notes: 'Cut into 1-inch florets (about 6 cups)',
    },    
    {
        id: '18',
        recipe_id: '2',
        ingredient: 'Canola Oil',
        quantity: '2',
        measurement: 'Tbsp',
        notes: 'Divided 1 Tbsp',
    },
    {
        id: '19',
        recipe_id: '2',
        ingredient: 'Ground Beef, 95% Lean',
        quantity: '1 1/2',
        measurement: 'lb',
        notes: '',
    },
    {
        id: '20',
        recipe_id: '2',
        ingredient: 'Onion',
        quantity: '1',
        measurement: 'each',
        notes: 'Chopped',
    },
    {
        id: '21',
        recipe_id: '2',
        ingredient: 'Worcestershire Sauce',
        quantity: '2',
        measurement: 'Tbsp',
        notes: '',
    },
    {
        id: '22',
        recipe_id: '2',
        ingredient: 'Garlic Powder',
        quantity: '1',
        measurement: 'tsp',
        notes: '',
    },
    {
        id: '23',
        recipe_id: '2',
        ingredient: 'Salt',
        quantity: '1 1/4',
        measurement: 'tsp',
        notes: 'Divided',
    },
    {
        id: '24',
        recipe_id: '2',
        ingredient: 'Milk, Lowfat',
        quantity: '4',
        measurement: 'cup',
        notes: '',
    },
    {
        id: '25',
        recipe_id: '2',
        ingredient: 'Cornstarch',
        quantity: '1/3',
        measurement: 'cup',
        notes: '',
    },
    {
        id: '26',
        recipe_id: '2',
        ingredient: 'Cheddar Cheese, Sharp, Shredded',
        quantity: '2',
        measurement: 'cup',
        notes: 'Preferably orange',
    },
    {
        id: '27',
        recipe_id: '2',
        ingredient: 'Tumeric, Ground',
        quantity: '1/4',
        measurement: 'tsp',
        notes: '',
    },
    {
        id: '28',
        recipe_id: '2',
        ingredient: 'Hash Browns, shredded, Frozen',
        quantity: '4',
        measurement: 'cup',
        notes: 'Or precooked shredded potatoes, (see Note)',
    },
    {
        id: '29',
        recipe_id: '2',
        ingredient: 'Egg',
        quantity: '1',
        measurement: 'each',
        notes: 'Lightly beaten',
    },
    {
        id: '30',
        recipe_id: '2',
        ingredient: 'Black Pepper, Ground',
        quantity: '1/2',
        measurement: 'tsp',
        notes: '',
    },
    {
        id: '31',
        recipe_id: '2',
        ingredient: 'Canola Oil',
        quantity: '2',
        measurement: 'Tbsp',
        notes: 'Or olive oil cooking spray',
    },
    {
        id: '32',
        recipe_id: '2',
        ingredient: 'Hungarian Paprika',
        quantity: '1/4',
        measurement: 'tsp',
        notes: 'Preferably hot',
    },
    {
        id: '33',
        recipe_id: '3',
        ingredient: 'Green Beans',
        quantity: '2 1/2',
        measurement: 'lb',
        notes: 'Trimmed and cut into 1- to 2-inch pieces (about 8 cups)',
    },
    {
        id: '34',
        recipe_id: '3',
        ingredient: 'Extra-Virgin Olive Oil',
        quantity: '3',
        measurement: 'Tbsp',
        notes: 'Divided',
    },
    {
        id: '35',
        recipe_id: '3',
        ingredient: 'Onion',
        quantity: '1',
        measurement: 'each',
        notes: 'Thinly Sliced',
    },
    {
        id: '36',
        recipe_id: '3',
        ingredient: 'All-Purpose Flour',
        quantity: '3',
        measurement: 'Tbsp',
        notes: '',
    },
    {
        id: '37',
        recipe_id: '3',
        ingredient: 'Salt',
        quantity: '3/4',
        measurement: 'tsp',
        notes: '',
    },
    {
        id: '38',
        recipe_id: '3',
        ingredient: 'Black Pepper, Ground',
        quantity: '1/4',
        measurement: 'tsp',
        notes: 'Or white',
    },
    {
        id: '39',
        recipe_id: '3',
        ingredient: 'Milk, Low-Fat',
        quantity: '2 1/2',
        measurement: 'cup',
        notes: 'Or white',
    },
    {
        id: '40',
        recipe_id: '3',
        ingredient: 'Breadcrumbs, Whole Wheat',
        quantity: '1 1/2',
        measurement: 'cup',
        notes: '(See Tips) or ½ cup shredded or crumbled cheese',
    },
    {
        id: '41',
        recipe_id: '4',
        ingredient: 'Canola Oil',
        quantity: '2',
        measurement: 'Tbsp',
        notes: 'Or olive oil cooking spray',
    },
    {
        id: '42',
        recipe_id: '4',
        ingredient: 'All-Purpose Flour',
        quantity: '1/4',
        measurement: 'cup',
        notes: '',
    },
    {
        id: '43',
        recipe_id: '4',
        ingredient: 'Egg',
        quantity: '2',
        measurement: 'each',
        notes: '',
    },
    {
        id: '44',
        recipe_id: '4',
        ingredient: 'Breadcrumbs',
        quantity: '1',
        measurement: 'cup',
        notes: 'Preferably whole-wheat (see Note)',
    },
    {
        id: '45',
        recipe_id: '4',
        ingredient: 'Chicken Tenders',
        quantity: '1',
        measurement: 'lb',
        notes: '',
    },
    {
        id: '46',
        recipe_id: '4',
        ingredient: 'Italian Seasoning',
        quantity: '1',
        measurement: 'Tbsp',
        notes: '',
    },
    {
        id: '47',
        recipe_id: '4',
        ingredient: 'Garlic Powder',
        quantity: '1',
        measurement: 'tsp',
        notes: '',
    },
    {
        id: '48',
        recipe_id: '4',
        ingredient: 'Salt',
        quantity: '1/4',
        measurement: 'tsp',
        notes: '',
    },
    {
        id: '49',
        recipe_id: '4',
        ingredient: 'Marinara Sauce',
        quantity: '1',
        measurement: 'cup',
        notes: 'Heated',
    },
    {
        id: '50',
        recipe_id: '5',
        ingredient: 'Whole Chicken',
        quantity: '10',
        measurement: 'lb',
        notes: '5 lbs each',
    },
    {
        id: '51',
        recipe_id: '5',
        ingredient: 'Kosher Salt',
        quantity: '1',
        measurement: 'Tbsp',
        notes: '',
    },
    {
        id: '52',
        recipe_id: '5',
        ingredient: 'Black Pepper, Ground',
        quantity: '1',
        measurement: 'Tbsp',
        notes: '',
    },
    {
        id: '53',
        recipe_id: '5',
        ingredient: 'Onion',
        quantity: '1/2',
        measurement: 'each',
        notes: '1 cup chopped',
    },
    {
        id: '54',
        recipe_id: '5',
        ingredient: 'Celery',
        quantity: '1',
        measurement: 'cup',
        notes: 'Chopped',
    },
    {
        id: '55',
        recipe_id: '5',
        ingredient: 'Carrots',
        quantity: '1',
        measurement: 'cup',
        notes: 'Chopped',
    },
    {
        id: '56',
        recipe_id: '5',
        ingredient: 'Extra-Virgin Olive Oil  ',
        quantity: '2',
        measurement: 'Tbsp',
        notes: '',
    },
    {
        id: '57',
        recipe_id: '6',
        ingredient: 'Black Pepper, Course Ground',
        quantity: '1',
        measurement: 'tsp',
        notes: '',
    },
    {
        id: '58',
        recipe_id: '6',
        ingredient: 'Salt',
        quantity: '1/2',
        measurement: 'tsp',
        notes: 'Divided',
    },
    {
        id: '59',
        recipe_id: '6',
        ingredient: 'Pork Chops, Boneless',
        quantity: '16',
        measurement: 'oz',
        notes: '1/2 inch thick, trimmed',
    },
    {
        id: '60',
        recipe_id: '6',
        ingredient: 'All-Purpose Flour',
        quantity: '3',
        measurement: 'Tbsp',
        notes: '',
    },
    {
        id: '61',
        recipe_id: '6',
        ingredient: 'Extra-Virgin Olive Oil',
        quantity: '2',
        measurement: 'Tbsp',
        notes: '',
    },
    {
        id: '62',
        recipe_id: '6',
        ingredient: 'Shallot',
        quantity: '1',
        measurement: 'each',
        notes: 'Minced',
    },
    {
        id: '63',
        recipe_id: '6',
        ingredient: 'Brandy',
        quantity: '1/2',
        measurement: 'cup',
        notes: '',
    },
    {
        id: '64',
        recipe_id: '6',
        ingredient: 'Sour Cream, Reduced Fat',
        quantity: '1/4',
        measurement: 'cup',
        notes: '',
    },
    {
        id: '65',
        recipe_id: '7',
        ingredient: 'Rib Chops, Bone-in',
        quantity: '1 3/4',
        measurement: 'lb',
        notes: '¾-inch-thick pork trimmed of fat',
    },
    {
        id: '66',
        recipe_id: '7',
        ingredient: 'Salt',
        quantity: '1/4',
        measurement: 'tsp',
        notes: '',
    },
    {
        id: '67',
        recipe_id: '7',
        ingredient: 'Black Pepper, Ground',
        quantity: '1/4',
        measurement: 'tsp',
        notes: '',
    },
    {
        id: '68',
        recipe_id: '7',
        ingredient: 'Canola Oil',
        quantity: '3',
        measurement: 'tsp',
        notes: 'Divided',
    },
    {
        id: '69',
        recipe_id: '7',
        ingredient: 'Onion',
        quantity: '1',
        measurement: 'each',
        notes: 'Diced',
    },
    {
        id: '70',
        recipe_id: '7',
        ingredient: 'Garlic Clove',
        quantity: '1',
        measurement: 'each',
        notes: 'Minced',
    },
    {
        id: '71',
        recipe_id: '7',
        ingredient: 'Orange Juice',
        quantity: '1/3',
        measurement: 'cup',
        notes: 'Minced',
    },
    {
        id: '72',
        recipe_id: '7',
        ingredient: 'Barbecue Sauce',
        quantity: '1/2',
        measurement: 'cup',
        notes: '(see tip)',
    },
    {
        id: '73',
        recipe_id: '8',
        ingredient: 'Apricots, Dried, Chopped',
        quantity: '1/2',
        measurement: 'cup',
        notes: '',
    },
    {
        id: '74',
        recipe_id: '8',
        ingredient: 'Sugar',
        quantity: '1/3',
        measurement: 'cup',
        notes: '',
    },
    {
        id: '75',
        recipe_id: '8',
        ingredient: 'Orange Zest',
        quantity: '1',
        measurement: 'tsp',
        notes: 'Slivered',
    },
    {
        id: '76',
        recipe_id: '8',
        ingredient: 'Water',
        quantity: '1',
        measurement: 'cup',
        notes: '',
    },
    {
        id: '77',
        recipe_id: '8',
        ingredient: 'Bulgur',
        quantity: '1/2',
        measurement: 'cup',
        notes: '',
    },
    {
        id: '78',
        recipe_id: '8',
        ingredient: 'Egg',
        quantity: '2',
        measurement: 'each',
        notes: 'Seperated',
    },
    {
        id: '79',
        recipe_id: '8',
        ingredient: 'Milk, Low-Fat',
        quantity: '2/3',
        measurement: 'each',
        notes: 'Seperated',
    },
    {
        id: '80',
        recipe_id: '8',
        ingredient: 'Brown Sugar',
        quantity: '2',
        measurement: 'Tbsp',
        notes: 'Seperated',
    },
    {
        id: '81',
        recipe_id: '8',
        ingredient: 'Pistachios, Toasted, Finely Chopped',
        quantity: '1/2',
        measurement: 'Tbsp',
        notes: 'Preferably Salted',
    },
    {
        id: '82',
        recipe_id: '9',
        ingredient: 'Melba Toasts, Plain',
        quantity: '15',
        measurement: 'each',
        notes: '(About 4 ounces; not Melba “snacks”)',
    },
    {
        id: '83',
        recipe_id: '9',
        ingredient: 'Walnut, Halves',
        quantity: '1/3',
        measurement: 'cup',
        notes: '',
    },
    {
        id: '84',
        recipe_id: '9',
        ingredient: 'Extra-Virgin Olive Oil',
        quantity: '2',
        measurement: 'Tbsp',
        notes: '',
    },
    {
        id: '85',
        recipe_id: '9',
        ingredient: 'Sugar',
        quantity: '1 1/3',
        measurement: 'Tbsp',
        notes: '',
    },
    {
        id: '86',
        recipe_id: '9',
        ingredient: 'Cream Cheese, Reduced Fat',
        quantity: '14',
        measurement: 'oz',
        notes: '',
    },
    {
        id: '87',
        recipe_id: '9',
        ingredient: 'Greek Yogurt, Non-Fat, Plain',
        quantity: '2 1/2',
        measurement: 'cup',
        notes: 'Or low-fat, (see Ingredient Note)',
    },
    {
        id: '88',
        recipe_id: '9',
        ingredient: 'Egg',
        quantity: '7',
        measurement: 'each',
        notes: 'Whites only',
    },
    {
        id: '89',
        recipe_id: '9',
        ingredient: 'Cinnamon, Ground',
        quantity: '1',
        measurement: 'tsp',
        notes: '',
    },
    {
        id: '90',
        recipe_id: '9',
        ingredient: 'Figs, Dried, Whole',
        quantity: '16',
        measurement: 'each',
        notes: '',
    },
    {
        id: '91',
        recipe_id: '9',
        ingredient: 'Water, Warm',
        quantity: '2',
        measurement: 'cup',
        notes: '',
    },
    {
        id: '92',
        recipe_id: '9',
        ingredient: 'Ouzo',
        quantity: '1/2',
        measurement: 'cup',
        notes: 'Mavrodaphne or port wine (see Ingredient Note)',
    },
    {
        id: '93',
        recipe_id: '9',
        ingredient: 'Rose Geranium Leaves',
        quantity: '2',
        measurement: 'each',
        notes: 'Plus more for garnish (optional; see Ingredient Note)',
    },
    {
        id: '94',
        recipe_id: '9',
        ingredient: 'Cinnamon Stick',
        quantity: '1',
        measurement: 'each',
        notes: '',
    },
    {
        id: '95',
        recipe_id: '9',
        ingredient: 'Orange Zest',
        quantity: '3',
        measurement: 'Tbsp',
        notes: '3-inch strip',
    },
]